// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidtermApi.Data;

namespace MidtermApi.Migrations
{
    [DbContext(typeof(VacationDbContext))]
    [Migration("20191114181425_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MidtermApi.Models.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("FamilyFriendly")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Outdoors")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Activity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityID = 1,
                            FamilyFriendly = 1,
                            Name = @"1) This is it. You’re about to walk into a memory. Soaring 520 feet skyward. The city actually, really, truly at your feet. Step up. Step out. Step beyond your comfort zone. And experience wonder on a higher level. Visit the Space Needle in the heart of Seattle. 
 2) When you and your friends arrive in Seattle by plane, cruise ship, car or Seattle-style bicycle, 'Ride the Ducks of Seattle' should be your first stop. In ninety minutes, you’ll see the top sights and hear about how the city developed into the tech-coffee-expensive-real-estate hub it is today. Before you start drinking your double tall, extra foam, skinny vanilla latte or posting photos when “the mountain’s out,” enjoy all that makes Seattle famous on the tour that was rated #1 City Tour for more than a decade.3) One of the few authentic farmer's markets in the United States, this hub of delicious scents, delectable eats and delightful personalities attracts nine million visitors a year. Take a tour of Pike Place Market and find outwhy this market has become a staple in Seattle. 
",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 2,
                            CityID = 1,
                            FamilyFriendly = 0,
                            Name = @"1) Fly high indoors at IFly. An exiciting indoors skydiving center located only mintues outside of Seattle 
2) Try to stay dry canoeing on Lake Washington at the University of Washington Waterfront Activities Center.
 3) Visit REI in downtown Seattle and try your luck at Rock Climbing 
",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 3,
                            CityID = 1,
                            FamilyFriendly = 1,
                            Name = "1) Visit the Seattle Art Museum in downtown Seattle._ 2) Visit the Seattle Aquarium located on Pier 59 on the Elliott Bay waterfront._ 3) Visit the Pacific Science Center.",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 4,
                            CityID = 1,
                            FamilyFriendly = 0,
                            Name = "1) Take a tour of Seattle underground with Bill Speidel's Underground Tour._ 2) Get some drinks at some great bars on Capitol Hill._ 3) Get a bite to eat with a great view at Six Seven Restaurant.",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 5,
                            CityID = 2,
                            FamilyFriendly = 1,
                            Name = "1) Visit the Buffalo Zoo._ 2) Swim, climb, and slide on a nautical-themed playground at the Buffalo Harbor State Park._ 3) Have some outdoor fun at Canalside, a master-planned neighborhood and festival marketplace within the inner harbor of Buffalo.",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 6,
                            CityID = 2,
                            FamilyFriendly = 0,
                            Name = @"1) Hop aboard on the Buffalo Pedal Tour, this people powered tour bus or boat for a fun filled time. On land and now on the water! Our professional drivers will guide you and your friends through the streets of Buffalo as you provide the energy by pedaling. 
2) Try to stay dry canoeing on Lake Washington at the University of Washington Waterfront Activities Center.
 3) Activity without family outdoors placeholder 
",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 7,
                            CityID = 2,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1.
 2) activity with family indoors placeholder #2.
 3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 8,
                            CityID = 2,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 9,
                            CityID = 3,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 10,
                            CityID = 3,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 11,
                            CityID = 3,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 12,
                            CityID = 3,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 13,
                            CityID = 4,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 14,
                            CityID = 4,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 15,
                            CityID = 4,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 16,
                            CityID = 4,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 17,
                            CityID = 5,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 18,
                            CityID = 5,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 19,
                            CityID = 5,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 20,
                            CityID = 5,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 21,
                            CityID = 6,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 22,
                            CityID = 6,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 23,
                            CityID = 6,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 24,
                            CityID = 6,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 25,
                            CityID = 7,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 26,
                            CityID = 7,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 27,
                            CityID = 7,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 28,
                            CityID = 7,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 29,
                            CityID = 8,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 30,
                            CityID = 8,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 31,
                            CityID = 8,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 32,
                            CityID = 8,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 33,
                            CityID = 9,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 34,
                            CityID = 9,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 35,
                            CityID = 9,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 36,
                            CityID = 9,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 37,
                            CityID = 10,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 38,
                            CityID = 10,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 39,
                            CityID = 10,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 40,
                            CityID = 10,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 41,
                            CityID = 11,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 42,
                            CityID = 11,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 43,
                            CityID = 11,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 44,
                            CityID = 11,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 45,
                            CityID = 12,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 46,
                            CityID = 12,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 47,
                            CityID = 12,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 48,
                            CityID = 13,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family indoors placeholder #1. 
2) activity without family indoors placeholder #2.
3) activity without family indoors placeholder #3.
 ",
                            Outdoors = 0
                        },
                        new
                        {
                            ID = 49,
                            CityID = 13,
                            FamilyFriendly = 0,
                            Name = @"1) activity without family outdoors placeholder #1. 
2) activity without family outdoors placeholder #2.
3) activity without family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 50,
                            CityID = 13,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family outdoors placeholder #1. 
2) activity with family outdoors placeholder #2. 
3) activity with family outdoors placeholder #3.
 ",
                            Outdoors = 1
                        },
                        new
                        {
                            ID = 51,
                            CityID = 13,
                            FamilyFriendly = 1,
                            Name = @"1) activity with family indoors placeholder #1. 
2) activity with family indoors placeholder #2.
3) activity with family indoors placeholder #3.
 ",
                            Outdoors = 0
                        });
                });

            modelBuilder.Entity("MidtermApi.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hot")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InUSA")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Seattle, a city on Puget Sound in the Pacific Northwest, is surrounded by water, mountains and evergreen forests, and contains thousands of acres of parkland. Washington State’s largest city, it’s home to a large tech industry, with Microsoft and Amazon headquartered in its metropolitan area. The futuristic Space Needle, a 1962 World’s Fair legacy, is its most iconic landmark. ",
                            Hot = 0,
                            ImageURL = "",
                            InUSA = 1,
                            Name = "Seattle, Washington",
                            Price = 2
                        },
                        new
                        {
                            ID = 2,
                            Description = "Buffalo is a city on the shores of Lake Erie in upstate New York. Its fine neoclassical, beaux arts and art deco architecture speaks to its history as an industrial capital in the early 20th century. Its landmarks include the 398-ft art deco City Hall, the Frank Lloyd Wright–designed Darwin D. Martin House and the Albright-Knox Art Gallery, a Greek Revival museum with works by Picasso and Warhol.",
                            Hot = 0,
                            ImageURL = "",
                            InUSA = 1,
                            Name = "Buffalo, New York",
                            Price = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Los Angeles is a sprawling Southern California city and the center of the nation’s film and television industry. Near its iconic Hollywood sign, studios such as Paramount Pictures, Universal and Warner Brothers offer behind-the-scenes tours. On Hollywood Boulevard, TCL Chinese Theatre displays celebrities’ hand- and footprints, the Walk of Fame honors thousands of luminaries and vendors sell maps to stars’ homes.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 1,
                            Name = "Los Angeles, California",
                            Price = 3
                        },
                        new
                        {
                            ID = 4,
                            Description = "New Delhi is an urban district of Delhi which serves as the capital of India and seat of all three branches of the Government of India. The foundation stone of the city was laid by Emperor George V during the Delhi Durbar of 1911. It was designed by British architects, Sir Edwin Lutyens and Sir Herbert Baker.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "New Delhi, India",
                            Price = 1
                        },
                        new
                        {
                            ID = 5,
                            Description = "Paris, France's capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. Beyond such landmarks as the Eiffel Tower and the 12th-century, Gothic Notre-Dame cathedral, the city is known for its cafe culture and designer boutiques along the Rue du Faubourg Saint-Honoré.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "Paris, France",
                            Price = 3
                        },
                        new
                        {
                            ID = 6,
                            Description = "Seoul, the capital of South Korea, is a huge metropolis where modern skyscrapers, high-tech subways and pop culture meet Buddhist temples, palaces and street markets. Notable attractions include futuristic Dongdaemun Design Plaza, a convention hall with curving architecture and a rooftop park; Gyeongbokgung Palace, which once had more than 7,000 rooms; and Jogyesa Temple, site of ancient locust and pine trees.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "Seoul, South Korea",
                            Price = 2
                        },
                        new
                        {
                            ID = 7,
                            Description = "Moscow, on the Moskva River in western Russia, is the nation’s cosmopolitan capital. In its historic core is the Kremlin, a complex that’s home to the president and tsarist treasures in the Armoury. Outside its walls is Red Square, Russia's symbolic center. It's home to Lenin’s Mausoleum, the State Historical Museum's comprehensive collection and St. Basil’s Cathedral, known for its colorful, onion-shaped domes.",
                            Hot = 0,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "Moscow, Russia",
                            Price = 2
                        },
                        new
                        {
                            ID = 8,
                            Description = "Orlando, a city in central Florida, is home to more than a dozen theme parks. Chief among its claims to fame is Walt Disney World, comprised of parks like the Magic Kingdom and Epcot, as well as water parks. Another major destination, Universal Orlando, offers Universal Studios and Islands of Adventure, with the Wizarding World of Harry Potter straddling both.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 1,
                            Name = "Orlando, Florida",
                            Price = 2
                        },
                        new
                        {
                            ID = 9,
                            Description = "Atlanta is the capital of the U.S. state of Georgia. It played an important part in both the Civil War and the 1960s Civil Rights Movement. Atlanta History Center chronicles the city's past, and the Martin Luther King Jr. National Historic Site is dedicated to the African-American leader’s life and times. Downtown, Centennial Olympic Park, built for the 1996 Olympics, encompasses the massive Georgia Aquarium.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 1,
                            Name = "Atlanta, Georgia",
                            Price = 1
                        },
                        new
                        {
                            ID = 10,
                            Description = "Denver, the capital of Colorado, is an American metropolis dating to the Old West era. Larimer Square, the city’s oldest block, features landmark 19th-century buildings. Museums include the Denver Art Museum, an ultramodern complex known for its collection of indigenous works, and the mansion of famed Titanic survivor Molly Brown. Denver is also a jumping-off point for ski resorts in the nearby Rocky Mountains.",
                            Hot = 0,
                            ImageURL = "",
                            InUSA = 1,
                            Name = "Denver, Colorado",
                            Price = 1
                        },
                        new
                        {
                            ID = 11,
                            Description = "Reykjavik, on the coast of Iceland, is the country's capital and largest city. It's home to the National and Saga museums, tracing Iceland’s Viking history. The striking concrete Hallgrimskirkja church and rotating Perlan glass dome offer sweeping views of the sea and nearby hills. Exemplifying the island’s volcanic activity is the geothermal Blue Lagoon spa, near the village of Grindavik.",
                            Hot = 0,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "Reykjavík, Iceland",
                            Price = 3
                        },
                        new
                        {
                            ID = 12,
                            Description = "Helsinki, Finland’s southern capital, sits on a peninsula in the Gulf of Finland. Its central avenue, Mannerheimintie, is flanked by institutions including the National Museum, tracing Finnish history from the Stone Age to the present. Also on Mannerheimintie are the imposing Parliament House and Kiasma, a contemporary art museum. Ornate red-brick Uspenski Cathedral overlooks a harbor.",
                            Hot = 0,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "Helsinki, Finland",
                            Price = 1
                        },
                        new
                        {
                            ID = 13,
                            Description = "Phuket, a rainforested, mountainous island in the Andaman Sea, has some of Thailand’s most popular beaches, mainly situated along the clear waters of the western shore. The island is home to many high-end seaside resorts, spas and restaurants. Phuket City, the capital, has old shophouses and busy markets. Patong, the main resort town, has many nightclubs, bars and discos.",
                            Hot = 1,
                            ImageURL = "",
                            InUSA = 0,
                            Name = "Phuket, Thailand",
                            Price = 2
                        });
                });

            modelBuilder.Entity("MidtermApi.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityID = 1,
                            Name = "Roy Street Commons",
                            Price = 1
                        },
                        new
                        {
                            ID = 2,
                            CityID = 1,
                            Name = "Hilton Seattle",
                            Price = 2
                        },
                        new
                        {
                            ID = 3,
                            CityID = 1,
                            Name = "Four Seasons Hotel",
                            Price = 3
                        },
                        new
                        {
                            ID = 4,
                            CityID = 2,
                            Name = "Motel 6 Buffalo Airport",
                            Price = 1
                        },
                        new
                        {
                            ID = 5,
                            CityID = 2,
                            Name = "Millennium Buffalo",
                            Price = 2
                        },
                        new
                        {
                            ID = 6,
                            CityID = 2,
                            Name = "Curtiss Hotel",
                            Price = 3
                        },
                        new
                        {
                            ID = 7,
                            CityID = 3,
                            Name = "Monterey Inn",
                            Price = 1
                        },
                        new
                        {
                            ID = 8,
                            CityID = 3,
                            Name = "Freehand Los Angeles",
                            Price = 2
                        },
                        new
                        {
                            ID = 9,
                            CityID = 3,
                            Name = "The Ritz-Carlton, Los Angeles",
                            Price = 3
                        },
                        new
                        {
                            ID = 10,
                            CityID = 4,
                            Name = "Suites Admiral",
                            Price = 1
                        },
                        new
                        {
                            ID = 11,
                            CityID = 4,
                            Name = "Haveli Dharampura",
                            Price = 3
                        },
                        new
                        {
                            ID = 12,
                            CityID = 4,
                            Name = "Hotel Diplomat",
                            Price = 2
                        },
                        new
                        {
                            ID = 13,
                            CityID = 5,
                            Name = "Le Regent Montmarte",
                            Price = 1
                        },
                        new
                        {
                            ID = 14,
                            CityID = 5,
                            Name = "Holiday Inn Paris",
                            Price = 2
                        },
                        new
                        {
                            ID = 15,
                            CityID = 5,
                            Name = "InterContinental Paris",
                            Price = 3
                        },
                        new
                        {
                            ID = 16,
                            CityID = 6,
                            Name = "Hongdae Chef Guesthouse",
                            Price = 1
                        },
                        new
                        {
                            ID = 17,
                            CityID = 6,
                            Name = "Tmark Hotel Myeongdong",
                            Price = 2
                        },
                        new
                        {
                            ID = 18,
                            CityID = 6,
                            Name = "Park Hyatt Seoul",
                            Price = 3
                        },
                        new
                        {
                            ID = 19,
                            CityID = 7,
                            Name = "Winterfell Hotel Tverskaya",
                            Price = 1
                        },
                        new
                        {
                            ID = 20,
                            CityID = 7,
                            Name = "Hilton Garden Inn Moscow Krasnoselskaya",
                            Price = 2
                        },
                        new
                        {
                            ID = 21,
                            CityID = 7,
                            Name = "The St. Regis Moscow Nikolskaya",
                            Price = 3
                        },
                        new
                        {
                            ID = 22,
                            CityID = 8,
                            Name = "Howard Johnson by Wyndham Lake Front Park Kissimmee",
                            Price = 1
                        },
                        new
                        {
                            ID = 23,
                            CityID = 8,
                            Name = "DoubleTree by Hilton Hotel at the Entrance to Universal Orlando",
                            Price = 2
                        },
                        new
                        {
                            ID = 24,
                            CityID = 8,
                            Name = "Grand Bohemian Hotel Orlando, Autograph Collection",
                            Price = 3
                        },
                        new
                        {
                            ID = 25,
                            CityID = 9,
                            Name = "Super 8 by Wyndham Austell/Six Flags",
                            Price = 1
                        },
                        new
                        {
                            ID = 26,
                            CityID = 9,
                            Name = "Crowne Plaza Atlanta-Airport",
                            Price = 2
                        },
                        new
                        {
                            ID = 27,
                            CityID = 9,
                            Name = "Four Seasons Hotel Atlanta",
                            Price = 3
                        },
                        new
                        {
                            ID = 28,
                            CityID = 10,
                            Name = "Ember Hostel",
                            Price = 1
                        },
                        new
                        {
                            ID = 29,
                            CityID = 10,
                            Name = "Home2 Suites by Hilton Denver International Airport",
                            Price = 2
                        },
                        new
                        {
                            ID = 30,
                            CityID = 10,
                            Name = "Four Seasons Hotel Denver",
                            Price = 3
                        },
                        new
                        {
                            ID = 31,
                            CityID = 11,
                            Name = "Reykjavik Downtown HI Hostel",
                            Price = 1
                        },
                        new
                        {
                            ID = 32,
                            CityID = 11,
                            Name = "Grand Hótel Reykjavík",
                            Price = 2
                        },
                        new
                        {
                            ID = 33,
                            CityID = 11,
                            Name = "Kvosin Downtown Hotel",
                            Price = 3
                        },
                        new
                        {
                            ID = 34,
                            CityID = 12,
                            Name = "Reykjavik Downtown HI Hostel",
                            Price = 1
                        },
                        new
                        {
                            ID = 35,
                            CityID = 12,
                            Name = "Grand Hótel Reykjavík",
                            Price = 2
                        },
                        new
                        {
                            ID = 36,
                            CityID = 12,
                            Name = "Kvosin Downtown Hotel",
                            Price = 3
                        },
                        new
                        {
                            ID = 37,
                            CityID = 13,
                            Name = "The Bukit",
                            Price = 1
                        },
                        new
                        {
                            ID = 38,
                            CityID = 13,
                            Name = "Andacura Beachfront collextion Panwa Phuket",
                            Price = 2
                        },
                        new
                        {
                            ID = 39,
                            CityID = 13,
                            Name = "The Westin Siray Bay Resort & Spa, Phuket",
                            Price = 3
                        });
                });

            modelBuilder.Entity("MidtermApi.Models.Plan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityID")
                        .HasColumnType("int");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationCode")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("CityID");

                    b.HasIndex("HotelID");

                    b.ToTable("SavedVacation");
                });

            modelBuilder.Entity("MidtermApi.Models.Plan", b =>
                {
                    b.HasOne("MidtermApi.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityID");

                    b.HasOne("MidtermApi.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID");

                    b.HasOne("MidtermApi.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID");
                });
#pragma warning restore 612, 618
        }
    }
}
